project_id = "bupwnylxuyaztitvrtbz"

[functions.process-document]
verify_jwt = true

[functions.document-processed]
verify_jwt = false

[functions.approve-ocr-pages]
verify_jwt = true

[functions.table-builder-agent]
verify_jwt = false
